### ISSUE TITLE
use_ssl error

### ISSUE THREAD

**Issue by boconnell2210** [xebialabs/puppet-xldeploy#58]
Does xldeploy process need to be stopped when the puppet agent runs?
I have the puppetmaster and xldeploy server on the same host.

When I run puppet without stopping the xldeploy process (centos 6.5 linux) I receive the following error:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: undefined method `use_ssl=' for #<Net::HTTP uc-01.wdts.local:4516 open=false> at /opt/wdts/puppet/production/modules/xldeploy/manifests/server/config.pp:110 on node uc-01.wdts.local
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

In my params.pp manifest I set it to false:
  $ssl                      = false
  $verify_ssl               = false

I would like to keep the xldeploy process running during puppet unless I need to update the puppet xldeploy mod.  

Thanks, in advance,
Billy

**Comment by WianVos** [comment]
Log a ticket .. I'll test it tonight if that is soon enough ..

Regards

Wian

Sent from my iPhone

On 12 Mar 2015, at 08:33, boconnell2210 <notifications@github.com<mailto:notifications@github.com>> wrote:


Does xldeploy process need to be stopped when the puppet agent runs?
I have the puppetmaster and xldeploy server on the same host.

When I run puppet without stopping the xldeploy process (centos 6.5 linux) I receive the following error:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: undefined method `use_ssl=' for # at /opt/wdts/puppet/production/modules/xldeploy/manifests/server/config.pp:110 on node uc-01.wdts.local
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

In my params.pp manifest I set it to false:
$ssl = false
$verify_ssl = false

I would like to keep the xldeploy process running during puppet unless I need to update the puppet xldeploy mod.

Thanks, in advance,
Billy

-

**Comment by boconnell2210** [comment]
It can wait until tonight.  Thanks.

I did open an issue, so it should be there, let me know if you can’t find it.

**Comment by WianVos** [comment]
found it :-)

**Comment by WianVos** [comment]
billy i can't find the code referenced in the error .. are u on a recent pull of the module ?

**Comment by boconnell2210** [comment]
I am using the latest, at least I thought I was, I will check on it.

**Comment by boconnell2210** [comment]
I have the latest, also using puppet version 3.7.4

2 things that I adjusted that is perhaps causing this issue as a requirement for our systems.
We use oracle java, not openjdk.
java -version
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

Also, we are in a closed environment, so I am downloading the xldeploy install packages from a local server, uc-01, not https://dist.xebialabs.com/xl-deploy/....

The files I adjusted from the defaults are:
lib/puppet/provider/xldeploy_plugin_netinstall/curl.rb
lib/puppet/type/xldeploy_plugin_netinstall.rb

I am going to look into that some more to figure out if the problem lies there.

**Comment by WianVos** [comment]
how are u doing on this?

**Comment by boconnell2210** [comment]
Well, I couldnt quite figure out where it was coming from.

I simply commented out line 110 mentioned above and I have yet to see an repercussions from it.


Here is the bit I commented out

  # ini settings
  ini_setting {
    'xldeploy.admin.password':
      setting => 'admin.password';
      #value   => to_xldeploy_md5($admin_password, $rest_url);

It allows me to not have to stop the service. 

You can close this issue, unless you want more information on it.

**Comment by WianVos** [comment]
No .. I won't close and I have a pretty good idea now where this is comming from .

Regards Wian

Sent from my iPhone

On 20 Mar 2015, at 18:44, boconnell2210 <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, I couldnt quite figure out where it was coming from.

I simply commented out line 110 mentioned above and I have yet to see an repercussions from it.

Here is the bit I commented out

# ini settings
ini_setting {
'xldeploy.admin.password':
setting => 'admin.password';
#value => to_xldeploy_md5($admin_password, $rest_url);

It allows me to not have to stop the service.

You can close this issue, unless you want more information on it.

-

**Comment by WianVos** [comment]
Billy can u do a run with the original code and a --trace flag ?

**Comment by boconnell2210** [comment]
Here are the trace results from the failure.  If you need more, please let me know.

Debug: Caching connection for https://uc-01.wdts.local:8140
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: undefined method `use_ssl=' for #<Net::HTTP uc-01.wdts.local:4516 open=false> at /opt/wdts/puppet/production/modules/xldeploy/manifests/server/config.pp:111 on node uc-01.wdts.local
/usr/lib/ruby/site_ruby/1.8/puppet/indirector/rest.rb:207:in `is_http_200?'
/usr/lib/ruby/site_ruby/1.8/puppet/indirector/rest.rb:100:in `find'
/usr/lib/ruby/site_ruby/1.8/puppet/indirector/indirection.rb:201:in `find'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:291:in `retrieve_new_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:327:in `thinmark'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:326:in `thinmark'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:290:in `retrieve_new_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:61:in `retrieve_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:104:in `prepare_and_retrieve_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:203:in `run_internal'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:132:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/context.rb:64:in `override'
/usr/lib/ruby/site_ruby/1.8/puppet.rb:244:in `override'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:131:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:47:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent/locker.rb:20:in `lock'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:47:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:117:in `with_client'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:44:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:82:in `run_in_fork'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:43:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:179:in `call'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:179:in `controlled_run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:41:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application/agent.rb:356:in `onetime'
/usr/lib/ruby/site_ruby/1.8/puppet/application/agent.rb:322:in `run_command'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:381:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:507:in `plugin_hook'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:381:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:488:in `exit_on_fail'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:381:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:146:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:92:in `execute'
/usr/bin/puppet:8
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
Debug: Using cached connection for https://uc-01.wdts.local:8140
Debug: Caching connection for https://uc-01.wdts.local:8140
Debug: Closing connection for https://uc-01.wdts.local:8140

**Comment by WianVos** [comment]
Billy this output makes no sense if u look at the last version of the module .. which one are u on .. and did u modilfy in any way ?

**Comment by ltutar** [comment]
[cid:54F8A1EA-DA07-44C4-99DB-83651F897DB6@home]

Met vriendelijke groet,

Levent


Levent Tutar * Senior Consultant
Xebia BV * Utrechtseweg 49 * 1213 TL Hilversum * The Netherlands
mobile +31 641452164  * office +31 35 5381921 * email ltutar@xebia.com<mailto:ltutar@xebia.com>

Visit Xebia on web at  www.xebia.com<http://www.xebia.com>

On 13 Apr 2015, at 22:42, WianVos <notifications@github.com<mailto:notifications@github.com>> wrote:


Billy this output makes no sense if u look at the last version of the module .. which one are u on .. and did u modilfy in any way ?

**Comment by ltutar** [comment]
Hi guys,

I just submitted a feature request.
https://github.com/xebialabs/puppet-xldeploy/issues/65

Is there anybody else working on this module actively on this module other than Wian? Why is nobody else reacting?

**Comment by ltutar** [comment]
@boconnell2210 Can we close this issue?
