### ISSUE TITLE
cluster snippet of jackrabbit-repository-db-mysql-cluster.xml.erb is missing a line

### ISSUE THREAD

**Issue by ltutar** [xebialabs/puppet-xldeploy#72]
Please add the line 
        <param name="schema" value="mysql" />

between 
<Journal class="org.apache.jackrabbit.core.journal.DatabaseJournal">
 </Journal>

Otherwise, you get the error in deployit.log:
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_79]
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_79]
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_79]

**Comment by WianVos** [comment]
done
